language: python

python:
    - "2.7"

before_install:
    - pip install pytest pytest-cov
    - pip install coveralls

install:
    - python setup.py develop

script:
    - py.test 

after_success:
    - coveralls
